name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aws_algo_trading
          environment-file: environment_linux.yml
          python-version: 3.12
          auto-activate-base: false

      - name: Create Config File
        run: |
          echo "${{ secrets.CONFIG_FILE }}" | base64 --decode > credentials  

      - name: Set AWS Credentials Environment Variable
        run: echo "AWS_SHARED_CREDENTIALS_FILE=$(pwd)/credentials" >> $GITHUB_ENV  # Set the environment variable

      - name: Run Tests
        run: |
            conda activate aws_algo_trading
            pytest

      - name: Clean up
        run: rm credentials

  build-windows:
    name: Windows
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: 3.12


      - name: Check file permissions
        run: |
          ls -l environment_windows.yml

      - name: Output environment file content
        run: cat environment_windows.yml

      - name: Create Conda environment
        run: conda env create -f environment_windows.yml

      - name: Create Config File
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.CONFIG_FILE }}")) | Out-File -FilePath credentials
        shell: pwsh

      - name: Verify AWS Profile in Credentials
        run: cat credentials | findstr "aws_algo_trader"

      - name: Check AWS CLI Version (Windows)
        run: aws --version

      - name: Set AWS Credentials Environment Variable
        run: echo "AWS_SHARED_CREDENTIALS_FILE=${{ github.workspace }}\\credentials" >> $GITHUB_ENV

      - name: Run Tests
        run: |
            conda activate aws_algo_trading
            pytest

      - name: Clean up
        run: Remove-Item credentials -Force -ErrorAction SilentlyContinue