name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aws_algo_trading
          environment-file: etc/environment_linux.yml
          python-version: 3.12
          auto-activate-base: false
      - run: |
          conda activate aws_algo_trading
          pytest