name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: aws_algo_trading
          environment-file: environment_linux.yml
          python-version: 3.12
          auto-activate-base: false

      - name: Create Config File
        run: |
          echo "${{ secrets.CONFIG_FILE }}" | base64 --decode > credentials  

      - name: Set AWS Credentials Environment Variable
        run: echo "AWS_SHARED_CREDENTIALS_FILE=$(pwd)/credentials" >> $GITHUB_ENV  # Set the environment variable

      - name: Run Tests
        run: |
            conda activate aws_algo_trading
            pytest

      - name: Clean up
        run: rm credentials


  build-windows:
    name: Windows
    runs-on: "windows-latest"
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: 3.12
          activate-environment: aws_algo_trading

      - name: Create Config File
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.CONFIG_FILE }}")) | Out-File -FilePath credentials -Encoding utf8

      - name: Set AWS Credentials Environment Variable
        run: |
          echo "AWS_SHARED_CREDENTIALS_FILE=${env:GITHUB_WORKSPACE}\credentials" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Debug AWS Configuration
        run: |
          echo "AWS_SHARED_CREDENTIALS_FILE: $env:AWS_SHARED_CREDENTIALS_FILE"
          Get-Content credentials
          aws configure list
          aws sts get-caller-identity

      - name: Run Tests
        shell: bash -l {0}
        run: |
          conda activate aws_algo_trading
          pytest

      - name: Clean up
        run: Remove-Item credentials -Force -ErrorAction SilentlyContinue
        if: always()